{
 "title": "CustomerAPI Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "jvm_type", "query": { "query": "metrics(jvm.*)" } },
   {
    "name": "heap_region",
    "query": "Tenured Gen,Eden Space,Survivor Space"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "{\"$jvm_type\", job=\"customer-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"customer-app\",area=\"heap\",id='${heap_region}'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"customer-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}